### ISSUE TITLE
Run phpunit locally

### ISSUE THREAD

**Issue by CarwynNelson** [BetterMood/better-mood#11]
There are currently quite a few phpunit tests running around the Moodle codebase. They require bringing the kitchen sink with you to run - but they do test the functionality of the codebase and so I do think they are going to be valuable at least during the initial phases.

We should get the tests running in the docker container (hopefully with one command) so that they can easily be run by anybody working on the project.

**Comment by michaelbiberich** [comment]
Information on automatic testing can be found in the [official docs](https://docs.moodle.org/dev/Testing), specifically

- [Unit testing with PHPUnit](https://docs.moodle.org/dev/Testing#Unit_tests)
- [Acceptance testing](https://docs.moodle.org/dev/Acceptance_testing) with Behat.

**Comment by JHeimbach** [comment]
I'll check if we can do that

**Comment by CarwynNelson** [comment]
I've already made a start on it but it looks like it will require some modifications to the base container (language packs)

Happy to help if needed.
