### ISSUE TITLE
PHP version requirement

### ISSUE THREAD

**Issue by michaelbiberich** [BetterMood/better-mood#13]
The [current stable version of moodle](https://download.moodle.org/releases/latest/) requires PHP 7.0 or newer.

This should be reflected in the `composer.json` with a version constraint like `"php": ">=7.0.0 <7.3.0"`.

Furthermore this minimum version requirement gives us the possibility to use certain features:

- [type hinting for primitives](http://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration)
- [return type declarations](http://php.net/manual/en/functions.returning-values.php#functions.returning-values.type-declaration)
- [strict type checking](http://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration.strict)

We should use these when refactoring existing code/write new code (wherever applicable).

This gives us several benefits:

- elimination for unnecessary type checking/conversion in calling code
- simplified assertions in tests
- more stability overall

Thoughts?

**Comment by CarwynNelson** [comment]
+1 from me.

As this project goes on I feel like I'm going to be a proponent of keeping backwards compatibility with Moodle for as long as possible.

That being said I see no reason to hamstring ourselves by sticking with older versions of PHP.

**Comment by JHeimbach** [comment]
done with #14
