### ISSUE TITLE
Move lib/horde to composer

### ISSUE THREAD

**Issue by nschmoyer** [BetterMood/better-mood#20]

**Comment by JHeimbach** [comment]
There is no packagist entry for horde, therefore it is atm not possible to move.

**Comment by CarwynNelson** [comment]
The main `horde/horde` repository is deprecated - but kept around for historical reasons. It seems that everything has been split out into separate repos now.

We could probably just link to a branch in `horde/horde` for now like we have done with the forks?

Alternatively we could try and identify which horde libraries are used by Moodle and only composer install those ones.

**Comment by JHeimbach** [comment]
@CarwynNelson thats maybe possible, i'll check that out
