### ISSUE TITLE
Create a CHANGELOG.md file

### ISSUE THREAD

**Issue by mistermuckle** [BetterMood/better-mood#59]
The only public change we’ve made so far (and at this stage we’ll have few others) is bumping the minimum PHP version to 7.1, but that needs to be recorded.

**Comment by michaelbiberich** [comment]
Here's a suggestion for a very well adapted Changelog Spec:

[Keep a Changelog 1.0.0](https://keepachangelog.com/en/1.0.0/)

**Comment by JHeimbach** [comment]
Closed #61
